In [2]:
%matplotlib inline
import pandas as pd
import numpy as np
from IPython.display import display
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('survey.csv')

In [4]:
df.shape

(1259, 27)

In [5]:
print(df.columns)
df

Index(['Timestamp', 'Age', 'Gender', 'Country', 'state', 'self_employed',
       'family_history', 'treatment', 'work_interfere', 'no_employees',
       'remote_work', 'tech_company', 'benefits', 'care_options',
       'wellness_program', 'seek_help', 'anonymity', 'leave',
       'mental_health_consequence', 'phys_health_consequence', 'coworkers',
       'supervisor', 'mental_health_interview', 'phys_health_interview',
       'mental_vs_physical', 'obs_consequence', 'comments'],
      dtype='object')

,Timestamp,Age,Gender,Country,state,self_employed,family_history,treatment,work_interfere,no_employees,...,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence,comments
0,2014-08-27 11:29:31,37,Female,United States,IL,NaN,No,Yes,Often,6-25,...,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No,NaN
1,2014-08-27 11:29:37,44,M,United States,IN,NaN,No,No,Rarely,More than 1000,...,Don't know,Maybe,No,No,No,No,No,Don't know,No,NaN
2,2014-08-27 11:29:44,32,Male,Canada,NaN,NaN,No,No,Rarely,6-25,...,Somewhat difficult,No,No,Yes,Yes,Yes,Yes,No,No,NaN
3,2014-08-27 11:29:46,31,Male,United Kingdom,NaN,NaN,Yes,Yes,Often,26-100,...,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,No,Yes,NaN
4,2014-08-27 11:30:22,31,Male,United States,TX,NaN,No,No,Never,100-500,...,Don't know,No,No,Some of them,Yes,Yes,Yes,Don't know,No,NaN
5,2014-08-27 11:31:22,33,Male,United States,TN,NaN,Yes,No,Sometimes,6-25,...,Don't know,No,No,Yes,Yes,No,Maybe,Don't know,No,NaN
6,2014-08-27 11:31:50,35,Female,United States,MI,NaN,Yes,Yes,Sometimes,1-5,...,Somewhat difficult,Maybe,Maybe,Some of them,No,No,No,Don't know,No,NaN
7,2014-08-27 11:32:05,39,M,Canada,NaN,NaN,No,No,Never,1-5,...,Don't know,No,No,No,No,No,No,No,No,NaN
8,2014-08-27 11:32:39,42,Female,United States,IL,NaN,Yes,Yes,Sometimes,100-500,...,Very difficult,Maybe,No,Yes,Yes,No,Maybe,No,No,NaN
9,2014-08-27 11:32:43,23,Male,Canada,NaN,NaN,No,No,Never,26-100,...,Don't know,No,No,Yes,Yes,Maybe,Maybe,Yes,No,NaN
10,2014-08-27 11:32:44,31,Male,United States,OH,NaN,No,Yes,Sometimes,6-25,...,Don't know,No,No,Some of them,Yes,No,No,Don't know,No,NaN
11,2014-08-27 11:32:49,29,male,Bulgaria,NaN,NaN,No,No,Never,100-500,...,Don't know,No,No,Yes,Yes,Yes,Yes,Don't know,No,NaN
12,2014-08-27 11:33:23,42,female,United States,CA,NaN,Yes,Yes,Sometimes,26-100,...,Somewhat difficult,Yes,Yes,Yes,Yes,Maybe,Maybe,No,Yes,NaN
13,2014-08-27 11:33:26,36,Male,United States,CT,NaN,Yes,No,Never,500-1000,...,Don't know,No,No,Yes,Yes,No,No,Don't know,No,I'm not on my company's health insurance which...
14,2014-08-27 11:33:57,27,Male,Canada,NaN,NaN,No,No,Never,6-25,...,Somewhat easy,No,No,Some of them,Some of them,Maybe,Yes,Yes,No,NaN
15,2014-08-27 11:34:00,29,female,United States,IL,NaN,Yes,Yes,Rarely,26-100,...,Somewhat easy,No,No,Yes,Some of them,Maybe,Maybe,Don't know,No,I have chronic low-level neurological issues t...
16,2014-08-27 11:34:20,23,Male,United Kingdom,NaN,NaN,No,Yes,Sometimes,26-100,...,Very easy,Maybe,No,Some of them,No,Maybe,Maybe,No,No,My company does provide healthcare but not to ...
17,2014-08-27 11:34:37,32,Male,United States,TN,NaN,No,Yes,Sometimes,6-25,...,Don't know,Maybe,No,Some of them,Yes,No,No,No,No,NaN
18,2014-08-27 11:34:53,46,male,United States,MD,Yes,Yes,No,Sometimes,1-5,...,Very easy,No,No,Yes,Yes,No,Yes,Yes,Yes,NaN
19,2014-08-27 11:35:08,36,Male,France,NaN,Yes,Yes,No,NaN,6-25,...,Somewhat easy,No,No,Some of them,Some of them,Maybe,Maybe,Don't know,No,NaN
20,2014-08-27 11:35:12,29,Male,United States,NY,No,Yes,Yes,Sometimes,100-500,...,Somewhat difficult,Maybe,No,Some of them,Some of them,No,No,No,No,NaN
21,2014-08-27 11:35:24,31,male,United States,NC,Yes,No,No,Never,1-5,...,Somewhat difficult,No,No,Some of them,Some of them,No,Maybe,Yes,No,NaN
22,2014-08-27 11:35:48,46,Male,United States,MA,No,No,Yes,Often,26-100,...,Don't know,Maybe,No,Some of them,Yes,No,Maybe,No,No,NaN
23,2014-08-27 11:36:24,41,Male,United States,IA,No,No,Yes,Never,More than 1000,...,Don't know,Maybe,No,No,No,No,Yes,Don't know,No,NaN
24,2014-08-27 11:36:48,33,male,United States,CA,No,Yes,Yes,Rarely,26-100,...,Don't know,No,No,Yes,Yes,No,Yes,Don't know,No,Relatively new job. Ask again later
25,2014-08-27 11:37:08,35,male,United States,TN,No,Yes,Yes,Sometimes,More than 1000,...,Very easy,Yes,No,Some of them,Yes,No,Yes,No,No,Sometimes I think about using drugs for my me...
26,2014-08-27 11:37:23,33,male,United States,TN,No,No,No,NaN,1-5,...,Don't know,Maybe,Maybe,Some of them,No,No,No,Don't know,No,NaN
27,2014-08-27 11:37:59,35,Female,United States,CA,No,Yes,Yes,Rarely,6-25,...,Don't know,No,No,Yes,Yes,Maybe,Maybe,Yes,No,NaN
28,2014-08-27 11:38:12,34,male,United States,OH,No,No,Yes,Sometimes,26-100,...,Somewhat difficult,No,No,Some of them,No,No,No,No,No,NaN
29,2014-08-27 11:38:18,37,Male,United Kingdom,NaN,No,No,No,Sometimes,6-25,...,Very difficult,Yes,Maybe,Some of them,No,No,Maybe,No,No,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1229,2015-02-22 02:40:32,39,Male,Greece,NaN,No,No,No,NaN,6-25,...,Don't know,Yes,No,No,No,No,No,Don't know,No,NaN
1230,2015-02-24 08:54:35,23,Female,United Kingdom,NaN,No,Yes,Yes,Sometimes,6-25,...,Very easy,No,No,Yes,Yes,Maybe,Maybe,Yes,No,NaN
1231,2015-02-24 08:58:08,24,Cis Man,United Kingdom,NaN,Yes,No,Yes,Sometimes,6-25,...,Don't know,Maybe,Maybe,Some of them,Some of them,No,Maybe,Don't know,Yes,NaN
1232,2015-02-24 09:00:56,25,Male,United Kingdom,NaN,No,Yes,Yes,Sometimes,More than 1000,...,Very easy,No,No,Yes,Yes,Yes,Yes,Yes,No,I work at a large university with a track reco...
1233,2015-02-24 09:13:49,23,Male,United Kingdom,NaN,No,No,Yes,Rarely,6-25,...,Don't know,No,No,Yes,Yes,No,Maybe,Don't know,No,NaN
1234,2015-02-24 09:15:13,24,"ostensibly male, unsure what that really means",United Kingdom,NaN,No,No,Yes,Sometimes,6-25,...,Don't know,Yes,Maybe,No,No,No,Maybe,Don't know,No,i'm in a country with social health care so my...
1235,2015-02-24 09:18:25,23,Male,Canada,NaN,No,No,Yes,Often,26-100,...,Don't know,Maybe,No,Yes,Some of them,No,No,Don't know,No,NaN
1236,2015-02-24 10:32:32,60,Male,United States,CA,No,No,Yes,Often,More than 1000,...,Somewhat easy,Maybe,Maybe,Some of them,No,No,Maybe,Don't know,No,NaN
1237,2015-02-26 05:44:16,28,male,Ireland,NaN,No,No,No,Sometimes,26-100,...,Don't know,Yes,Maybe,No,No,No,No,No,Yes,NaN
1238,2015-04-02 15:47:43,28,Male,United States,TN,No,Yes,Yes,Often,More than 1000,...,Somewhat easy,Yes,Maybe,Some of them,Yes,No,No,No,Yes,NaN
1239,2015-04-04 11:22:05,30,male,Netherlands,NaN,No,No,No,Sometimes,500-1000,...,Don't know,Maybe,No,Yes,Yes,Maybe,Yes,Don't know,No,NaN
1240,2015-04-06 14:58:29,31,male,Germany,NaN,No,Yes,Yes,Sometimes,100-500,...,Somewhat easy,No,No,Some of them,No,No,No,Don't know,No,NaN
1241,2015-04-11 14:35:22,31,Male,Poland,NaN,Yes,No,Yes,Often,6-25,...,Somewhat easy,Maybe,No,Some of them,No,No,No,Don't know,No,NaN
1242,2015-04-23 14:03:51,28,Male,Ireland,NaN,No,No,Yes,Rarely,26-100,...,Don't know,Maybe,No,No,No,No,Maybe,Don't know,No,NaN
1243,2015-05-05 14:22:18,43,f,United States,FL,No,Yes,Yes,Rarely,More than 1000,...,Don't know,No,No,Some of them,Yes,No,No,Don't know,No,NaN
1244,2015-05-05 15:16:25,32,female,United Kingdom,NaN,No,No,No,NaN,More than 1000,...,Don't know,Maybe,No,Some of them,Yes,No,Yes,No,No,NaN
1245,2015-05-06 10:14:50,22,Male,Australia,NaN,No,Yes,Yes,Often,100-500,...,Don't know,Maybe,Maybe,No,Yes,No,Maybe,Don't know,Yes,In australia all organisations of a certain si...
1246,2015-05-06 16:55:58,32,Male,United States,OR,No,No,No,Never,100-500,...,Somewhat easy,No,No,No,Some of them,Maybe,Yes,Don't know,No,NaN
1247,2015-05-07 10:08:50,36,male,Finland,NaN,No,No,Yes,Often,6-25,...,Very difficult,Yes,No,Some of them,No,No,Maybe,Don't know,Yes,NaN
1248,2015-06-25 12:24:31,41,Female,United States,WA,No,Yes,Yes,Sometimes,26-100,...,Don't know,Yes,Maybe,No,No,No,No,Don't know,No,NaN
1249,2015-07-22 18:57:54,30,M,United States,CA,No,Yes,Yes,Sometimes,26-100,...,Very easy,No,No,Yes,Yes,Maybe,Maybe,Yes,No,Bipolar disorder
1250,2015-07-27 23:25:34,30,Male,United States,CA,Yes,Yes,Yes,Often,26-100,...,Don't know,No,No,Some of them,Yes,Maybe,Maybe,Yes,No,NaN
1251,2015-08-17 09:38:35,36,Male,South Africa,NaN,No,Yes,Yes,Often,100-500,...,Somewhat easy,No,No,Some of them,Yes,No,Yes,Yes,No,NaN
1252,2015-08-20 16:52:09,29,male,United States,NC,No,Yes,Yes,Sometimes,100-500,...,Don't know,Yes,No,Some of them,No,No,Maybe,No,No,NaN
1253,2015-08-25 19:59:38,36,Male,United States,UT,No,Yes,No,Rarely,More than 1000,...,Somewhat easy,Maybe,Maybe,Some of them,Some of them,No,No,Don't know,No,NaN
1254,2015-09-12 11:17:21,26,male,United Kingdom,NaN,No,No,Yes,NaN,26-100,...,Somewhat easy,No,No,Some of them,Some of them,No,No,Don't know,No,NaN
1255,2015-09-26 01:07:35,32,Male,United States,IL,No,Yes,Yes,Often,26-100,...,Somewhat difficult,No,No,Some of them,Yes,No,No,Yes,No,NaN
1256,2015-11-07 12:36:58,34,male,United States,CA,No,Yes,Yes,Sometimes,More than 1000,...,Somewhat difficult,Yes,Yes,No,No,No,No,No,No,NaN
1257,2015-11-30 21:25:06,46,f,United States,NC,No,No,No,NaN,100-500,...,Don't know,Yes,No,No,No,No,No,No,No,NaN
1258,2016-02-01 23:04:31,25,Male,United States,IL,No,Yes,Yes,Sometimes,26-100,...,Don't know,Maybe,No,Some of them,No,No,No,Don't know,No,NaN

In [6]:
df.isnull().sum()

Timestamp                       0
Age                             0
Gender                          0
Country                         0
state                         515
self_employed                  18
family_history                  0
treatment                       0
work_interfere                264
no_employees                    0
remote_work                     0
tech_company                    0
benefits                        0
care_options                    0
wellness_program                0
seek_help                       0
anonymity                       0
leave                           0
mental_health_consequence       0
phys_health_consequence         0
coworkers                       0
supervisor                      0
mental_health_interview         0
phys_health_interview           0
mental_vs_physical              0
obs_consequence                 0
comments                     1095
dtype: int64

In [7]:
for col in df.columns:
    if col == 'Timestamp' or col == 'comments' :
        continue;
    print(col + ':\n' + str(df[col].unique().tolist()) + '\n')

Age:
[37, 44, 32, 31, 33, 35, 39, 42, 23, 29, 36, 27, 46, 41, 34, 30, 40, 38, 50, 24, 18, 28, 26, 22, 19, 25, 45, 21, -29, 43, 56, 60, 54, 329, 55, 99999999999, 48, 20, 57, 58, 47, 62, 51, 65, 49, -1726, 5, 53, 61, 8, 11, -1, 72]

Gender:
['Female', 'M', 'Male', 'male', 'female', 'm', 'Male-ish', 'maile', 'Trans-female', 'Cis Female', 'F', 'something kinda male?', 'Cis Male', 'Woman', 'f', 'Mal', 'Male (CIS)', 'queer/she/they', 'non-binary', 'Femake', 'woman', 'Make', 'Nah', 'All', 'Enby', 'fluid', 'Genderqueer', 'Female ', 'Androgyne', 'Agender', 'cis-female/femme', 'Guy (-ish) ^_^', 'male leaning androgynous', 'Male ', 'Man', 'Trans woman', 'msle', 'Neuter', 'Female (trans)', 'queer', 'Female (cis)', 'Mail', 'cis male', 'A little about you', 'Malr', 'p', 'femail', 'Cis Man', 'ostensibly male, unsure what that really means']

Country:
['United States', 'Canada', 'United Kingdom', 'Bulgaria', 'France', 'Portugal', 'Netherlands', 'Switzerland', 'Poland', 'Australia', 'Germany', 'Russia', 'Mexico', 'Brazil', 'Slovenia', 'Costa Rica', 'Austria', 'Ireland', 'India', 'South Africa', 'Italy', 'Sweden', 'Colombia', 'Latvia', 'Romania', 'Belgium', 'New Zealand', 'Zimbabwe', 'Spain', 'Finland', 'Uruguay', 'Israel', 'Bosnia and Herzegovina', 'Hungary', 'Singapore', 'Japan', 'Nigeria', 'Croatia', 'Norway', 'Thailand', 'Denmark', 'Bahamas, The', 'Greece', 'Moldova', 'Georgia', 'China', 'Czech Republic', 'Philippines']

state:
['IL', 'IN', nan, 'TX', 'TN', 'MI', 'OH', 'CA', 'CT', 'MD', 'NY', 'NC', 'MA', 'IA', 'PA', 'WA', 'WI', 'UT', 'NM', 'OR', 'FL', 'MN', 'MO', 'AZ', 'CO', 'GA', 'DC', 'NE', 'WV', 'OK', 'KS', 'VA', 'NH', 'KY', 'AL', 'NV', 'NJ', 'SC', 'VT', 'SD', 'ID', 'MS', 'RI', 'WY', 'LA', 'ME']

self_employed:
[nan, 'Yes', 'No']

family_history:
['No', 'Yes']

treatment:
['Yes', 'No']

work_interfere:
['Often', 'Rarely', 'Never', 'Sometimes', nan]

no_employees:
['6-25', 'More than 1000', '26-100', '100-500', '1-5', '500-1000']

remote_work:
['No', 'Yes']

tech_company:
['Yes', 'No']

benefits:
['Yes', "Don't know", 'No']

care_options:
['Not sure', 'No', 'Yes']

wellness_program:
['No', "Don't know", 'Yes']

seek_help:
['Yes', "Don't know", 'No']

anonymity:
['Yes', "Don't know", 'No']

leave:
['Somewhat easy', "Don't know", 'Somewhat difficult', 'Very difficult', 'Very easy']

mental_health_consequence:
['No', 'Maybe', 'Yes']

phys_health_consequence:
['No', 'Yes', 'Maybe']

coworkers:
['Some of them', 'No', 'Yes']

supervisor:
['Yes', 'No', 'Some of them']

mental_health_interview:
['No', 'Yes', 'Maybe']

phys_health_interview:
['Maybe', 'No', 'Yes']

mental_vs_physical:
['Yes', "Don't know", 'No']

obs_consequence:
['No', 'Yes']

In [8]:
# Genderの名寄せ
col = "Gender"
df[col].replace("All","all", inplace=True)
df_gender = pd.crosstab(index=df["treatment"], columns=df[col], margins=True)
display(df_gender.T.sort_values("All",ascending=False))

treatment                                        No  Yes   All
Gender
All                                             622  637  1259
Male                                            330  285   615
male                                            112   94   206
Female                                           37   84   121
M                                                69   47   116
female                                           16   46    62
F                                                12   26    38
m                                                20   14    34
f                                                 6    9    15
Make                                              1    3     4
Male                                              1    2     3
Woman                                             2    1     3
Female (trans)                                    0    2     2
Cis Male                                          0    2     2
Man                                               2    0     2
Female                                            1    1     2
non-binary                                        0    1     1
cis-female/femme                                  0    1     1
p                                                 0    1     1
femail                                            1    0     1
fluid                                             0    1     1
maile                                             1    0     1
ostensibly male, unsure what that really means    0    1     1
woman                                             0    1     1
something kinda male?                             1    0     1
queer                                             0    1     1
male leaning androgynous                          1    0     1
cis male                                          1    0     1
msle                                              1    0     1
queer/she/they                                    0    1     1
A little about you                                0    1     1
all                                               0    1     1
Guy (-ish) ^_^                                    0    1     1
Androgyne                                         0    1     1
Cis Female                                        0    1     1
Cis Man                                           0    1     1
Enby                                              0    1     1
Femake                                            1    0     1
Female (cis)                                      1    0     1
Genderqueer                                       1    0     1
Mail                                              1    0     1
Trans-female                                      1    0     1
Mal                                               1    0     1
Male (CIS)                                        1    0     1
Male-ish                                          0    1     1
Malr                                              0    1     1
Agender                                           0    1     1
Neuter                                            0    1     1
Trans woman                                       0    1     1
Nah                                               0    1     1

In [9]:
df["Gender2"] = df["Gender"].map({"Male":"Male","Female":"Female","male":"Male","female":"Female","M":"Male","F":"Female"})

In [10]:
col = "Gender2"
df_gender = pd.crosstab(index=df["treatment"], columns=df[col], margins=True)
display(df_gender)

Gender2    Female  Male   All
treatment
No             65   511   576
Yes           156   426   582
All           221   937  1158

In [18]:
# ageの外れ値
df.isnull().sum()

Timestamp                       0
Age                             0
Gender                          0
Country                         0
state                         515
self_employed                  18
family_history                  0
treatment                       0
work_interfere                264
no_employees                    0
remote_work                     0
tech_company                    0
benefits                        0
care_options                    0
wellness_program                0
seek_help                       0
anonymity                       0
leave                           0
mental_health_consequence       0
phys_health_consequence         0
coworkers                       0
supervisor                      0
mental_health_interview         0
phys_health_interview           0
mental_vs_physical              0
obs_consequence                 0
comments                     1095
Gender2                       101
dtype: int64

In [29]:
df2= df.dropna(subset=["Gender2"])

In [33]:
df[(df["Age"]<0)]

,Timestamp,Age,Gender,Country,state,self_employed,family_history,treatment,work_interfere,no_employees,...,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence,comments,Gender2
143,2014-08-27 12:39:14,-29,Male,United States,MN,No,No,No,NaN,More than 1000,...,No,No,Some of them,Yes,No,No,Don't know,No,NaN,Male
715,2014-08-28 10:07:53,-1726,male,United Kingdom,NaN,No,No,Yes,Sometimes,26-100,...,Yes,No,No,No,No,Maybe,Don't know,No,NaN,Male
1127,2014-08-30 20:55:11,-1,p,United States,AL,Yes,Yes,Yes,Often,1-5,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,password: testered,NaN

Timestamp                       0
Age                             0
Gender                          0
Country                         0
state                         477
self_employed                  18
family_history                  0
treatment                       0
work_interfere                243
no_employees                    0
remote_work                     0
tech_company                    0
benefits                        0
care_options                    0
wellness_program                0
seek_help                       0
anonymity                       0
leave                           0
mental_health_consequence       0
phys_health_consequence         0
coworkers                       0
supervisor                      0
mental_health_interview         0
phys_health_interview           0
mental_vs_physical              0
obs_consequence                 0
comments                     1015
Gender2                         0
dtype: int64